#!/bin/sh

chmod 755 /usr/lib/enigma2/python/Plugins/SystemPlugins/PanelAIO/install_archive_script.sh 2>/dev/null || true
chmod 755 /usr/lib/enigma2/python/Plugins/SystemPlugins/PanelAIO/installer.sh 2>/dev/null || true
chmod 755 /usr/lib/enigma2/python/Plugins/SystemPlugins/PanelAIO/update_satellites_xml.sh 2>/dev/null || true

rm -rf /usr/lib/enigma2/python/Plugins/Extensions/PanelAIO 2>/dev/null || true
find /usr/lib/enigma2/python/Plugins/SystemPlugins/PanelAIO -type d -name __pycache__ -exec rm -rf {} \; 2>/dev/null || true
find /usr/lib/enigma2/python/Plugins/SystemPlugins/PanelAIO -type f -name "*.pyc" -delete 2>/dev/null || true

exit 0
