#!/bin/sh
DST=/usr/lib/enigma2/python/Plugins/SystemPlugins/PanelAIO
chmod 755 "$DST/install_archive_script.sh" 2>/dev/null || true
chmod 755 "$DST/installer.sh" 2>/dev/null || true
chmod 755 "$DST/update_satellites_xml.sh" 2>/dev/null || true
find "$DST" -type f -name "*.sh" -exec chmod 755 {} \; 2>/dev/null || true
find "$DST" -type f -name "*.py" -exec chmod 644 {} \; 2>/dev/null || true
find "$DST" -type f -name "*.png" -exec chmod 644 {} \; 2>/dev/null || true
find "$DST" -type d -name __pycache__ -exec rm -rf {} \; 2>/dev/null || true
find "$DST" -type f \( -name "*.pyc" -o -name "*.pyo" \) -delete 2>/dev/null || true
sync || true
exit 0
